[package]
name = "rolling_stats"
version = "0.1.0"
edition = "2021"
authors = ["Jakub HornÃ¡Äek <hornacek.jakub@gmail.com>"]
keywords = ["statistics", "rolling", "window", "no_std"]

[features]
std = []

[dependencies]
arraydeque = { version = "0.5", default-features = false }
arrayvec = "0.7"
const_format = "0.2"
endi = { version = "1.1", default-features = false }
rand = { version = "0.8", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
rand_distr = { version = "0.4", default-features = false }

[dev-dependencies]
rv = "0.17.0"

